// Arca WireGuard Network Service Protocol
// gRPC API for WireGuard-based container networking

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/wireguard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a WireGuard hub interface
type CreateHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Private key for this container's WireGuard interface
	// Base64-encoded Curve25519 key (44 chars)
	PrivateKey string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Listen port for WireGuard (default: 51820)
	ListenPort uint32 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Container's IP address on first network (assigned to wg0)
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Network CIDR for the first network (e.g., "172.18.0.0/16")
	NetworkCidr   string `protobuf:"bytes,4,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHubRequest) Reset() {
	*x = CreateHubRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHubRequest) ProtoMessage() {}

func (x *CreateHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHubRequest.ProtoReflect.Descriptor instead.
func (*CreateHubRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHubRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CreateHubRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *CreateHubRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateHubRequest) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

type CreateHubResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Public key for this container (for peer configuration)
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Interface name created (should be "wg0")
	Interface     string `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHubResponse) Reset() {
	*x = CreateHubResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHubResponse) ProtoMessage() {}

func (x *CreateHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHubResponse.ProtoReflect.Descriptor instead.
func (*CreateHubResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHubResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateHubResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateHubResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateHubResponse) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

// Request to add a network to the container
type AddNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID (Docker network ID)
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Peer endpoint (hub's vmnet IP address, e.g., "192.168.65.5:51820")
	PeerEndpoint string `protobuf:"bytes,2,opt,name=peer_endpoint,json=peerEndpoint,proto3" json:"peer_endpoint,omitempty"`
	// Peer's public key (Base64-encoded)
	PeerPublicKey string `protobuf:"bytes,3,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	// IP address for this container on this network
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Network CIDR for allowed-ips routing (e.g., "172.19.0.0/16")
	NetworkCidr string `protobuf:"bytes,5,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	// Gateway IP for this network (for routing)
	Gateway       string `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkRequest) Reset() {
	*x = AddNetworkRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkRequest) ProtoMessage() {}

func (x *AddNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{2}
}

func (x *AddNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AddNetworkRequest) GetPeerEndpoint() string {
	if x != nil {
		return x.PeerEndpoint
	}
	return ""
}

func (x *AddNetworkRequest) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *AddNetworkRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AddNetworkRequest) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *AddNetworkRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type AddNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of networks now configured
	TotalNetworks uint32 `protobuf:"varint,3,opt,name=total_networks,json=totalNetworks,proto3" json:"total_networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkResponse) Reset() {
	*x = AddNetworkResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkResponse) ProtoMessage() {}

func (x *AddNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{3}
}

func (x *AddNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddNetworkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddNetworkResponse) GetTotalNetworks() uint32 {
	if x != nil {
		return x.TotalNetworks
	}
	return 0
}

// Request to remove a network from the container
type RemoveNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID to remove
	NetworkId     string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkRequest) Reset() {
	*x = RemoveNetworkRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkRequest) ProtoMessage() {}

func (x *RemoveNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

type RemoveNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of networks still configured
	RemainingNetworks uint32 `protobuf:"varint,3,opt,name=remaining_networks,json=remainingNetworks,proto3" json:"remaining_networks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveNetworkResponse) Reset() {
	*x = RemoveNetworkResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkResponse) ProtoMessage() {}

func (x *RemoveNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveNetworkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemoveNetworkResponse) GetRemainingNetworks() uint32 {
	if x != nil {
		return x.RemainingNetworks
	}
	return 0
}

// Request to update allowed IPs for multi-network routing
// Called when containers join/leave networks to update routing table
type UpdateAllowedIPsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Complete set of allowed IP ranges for this peer
	// Each entry is a CIDR (e.g., "172.18.0.0/16", "172.19.0.0/16")
	AllowedCidrs []string `protobuf:"bytes,1,rep,name=allowed_cidrs,json=allowedCidrs,proto3" json:"allowed_cidrs,omitempty"`
	// Peer public key to update (identifies which peer to configure)
	PeerPublicKey string `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAllowedIPsRequest) Reset() {
	*x = UpdateAllowedIPsRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllowedIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowedIPsRequest) ProtoMessage() {}

func (x *UpdateAllowedIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowedIPsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAllowedIPsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAllowedIPsRequest) GetAllowedCidrs() []string {
	if x != nil {
		return x.AllowedCidrs
	}
	return nil
}

func (x *UpdateAllowedIPsRequest) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

type UpdateAllowedIPsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of CIDR ranges now allowed
	TotalAllowed  uint32 `protobuf:"varint,3,opt,name=total_allowed,json=totalAllowed,proto3" json:"total_allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAllowedIPsResponse) Reset() {
	*x = UpdateAllowedIPsResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllowedIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowedIPsResponse) ProtoMessage() {}

func (x *UpdateAllowedIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowedIPsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAllowedIPsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAllowedIPsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAllowedIPsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateAllowedIPsResponse) GetTotalAllowed() uint32 {
	if x != nil {
		return x.TotalAllowed
	}
	return 0
}

// Request to delete the WireGuard hub
type DeleteHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Force deletion even if there are active networks
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHubRequest) Reset() {
	*x = DeleteHubRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHubRequest) ProtoMessage() {}

func (x *DeleteHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHubRequest.ProtoReflect.Descriptor instead.
func (*DeleteHubRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteHubRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteHubResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHubResponse) Reset() {
	*x = DeleteHubResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHubResponse) ProtoMessage() {}

func (x *DeleteHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHubResponse.ProtoReflect.Descriptor instead.
func (*DeleteHubResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteHubResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteHubResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request WireGuard status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_wireguard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{10}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Number of networks configured
	NetworkCount uint32 `protobuf:"varint,2,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	// WireGuard interface status
	Interface *InterfaceStatus `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	// Peer statistics (one per network)
	Peers         []*PeerStatus `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_wireguard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNetworkCount() uint32 {
	if x != nil {
		return x.NetworkCount
	}
	return 0
}

func (x *GetStatusResponse) GetInterface() *InterfaceStatus {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *GetStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type InterfaceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interface name (should be "wg0")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Public key
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Listen port
	ListenPort uint32 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// IP addresses assigned to interface
	IpAddresses   []string `protobuf:"bytes,4,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_proto_wireguard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStatus.ProtoReflect.Descriptor instead.
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{12}
}

func (x *InterfaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InterfaceStatus) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *InterfaceStatus) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type PeerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID this peer represents
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Peer public key
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Peer endpoint (IP:port)
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Allowed IPs for this peer
	AllowedIps []string `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// Latest handshake timestamp (Unix seconds, 0 if never)
	LatestHandshake uint64 `protobuf:"varint,5,opt,name=latest_handshake,json=latestHandshake,proto3" json:"latest_handshake,omitempty"`
	// Transfer statistics
	Stats         *TransferStats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_proto_wireguard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{13}
}

func (x *PeerStatus) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *PeerStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLatestHandshake() uint64 {
	if x != nil {
		return x.LatestHandshake
	}
	return 0
}

func (x *PeerStatus) GetStats() *TransferStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TransferStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes received from this peer
	BytesReceived uint64 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Bytes sent to this peer
	BytesSent uint64 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Persistent keepalive interval (seconds, 0 if disabled)
	PersistentKeepalive uint32 `protobuf:"varint,3,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransferStats) Reset() {
	*x = TransferStats{}
	mi := &file_proto_wireguard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStats) ProtoMessage() {}

func (x *TransferStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStats.ProtoReflect.Descriptor instead.
func (*TransferStats) Descriptor() ([]byte, []int) {
	return file_proto_wireguard_proto_rawDescGZIP(), []int{14}
}

func (x *TransferStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TransferStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TransferStats) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

var File_proto_wireguard_proto protoreflect.FileDescriptor

const file_proto_wireguard_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wireguard.proto\x12\x11arca.wireguard.v1\"\x96\x01\n" +
	"\x10CreateHubRequest\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12!\n" +
	"\fnetwork_cidr\x18\x04 \x01(\tR\vnetworkCidr\"\x80\x01\n" +
	"\x11CreateHubResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\"\xdb\x01\n" +
	"\x11AddNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rpeer_endpoint\x18\x02 \x01(\tR\fpeerEndpoint\x12&\n" +
	"\x0fpeer_public_key\x18\x03 \x01(\tR\rpeerPublicKey\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12!\n" +
	"\fnetwork_cidr\x18\x05 \x01(\tR\vnetworkCidr\x12\x18\n" +
	"\agateway\x18\x06 \x01(\tR\agateway\"k\n" +
	"\x12AddNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0etotal_networks\x18\x03 \x01(\rR\rtotalNetworks\"5\n" +
	"\x14RemoveNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\"v\n" +
	"\x15RemoveNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x12remaining_networks\x18\x03 \x01(\rR\x11remainingNetworks\"f\n" +
	"\x17UpdateAllowedIPsRequest\x12#\n" +
	"\rallowed_cidrs\x18\x01 \x03(\tR\fallowedCidrs\x12&\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\tR\rpeerPublicKey\"o\n" +
	"\x18UpdateAllowedIPsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rtotal_allowed\x18\x03 \x01(\rR\ftotalAllowed\"(\n" +
	"\x10DeleteHubRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"C\n" +
	"\x11DeleteHubResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10GetStatusRequest\"\xc9\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rnetwork_count\x18\x02 \x01(\rR\fnetworkCount\x12@\n" +
	"\tinterface\x18\x03 \x01(\v2\".arca.wireguard.v1.InterfaceStatusR\tinterface\x123\n" +
	"\x05peers\x18\x04 \x03(\v2\x1d.arca.wireguard.v1.PeerStatusR\x05peers\"\x88\x01\n" +
	"\x0fInterfaceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12!\n" +
	"\fip_addresses\x18\x04 \x03(\tR\vipAddresses\"\xea\x01\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12)\n" +
	"\x10latest_handshake\x18\x05 \x01(\x04R\x0flatestHandshake\x126\n" +
	"\x05stats\x18\x06 \x01(\v2 .arca.wireguard.v1.TransferStatsR\x05stats\"\x88\x01\n" +
	"\rTransferStats\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x121\n" +
	"\x14persistent_keepalive\x18\x03 \x01(\rR\x13persistentKeepalive2\xc6\x04\n" +
	"\x10WireGuardService\x12V\n" +
	"\tCreateHub\x12#.arca.wireguard.v1.CreateHubRequest\x1a$.arca.wireguard.v1.CreateHubResponse\x12Y\n" +
	"\n" +
	"AddNetwork\x12$.arca.wireguard.v1.AddNetworkRequest\x1a%.arca.wireguard.v1.AddNetworkResponse\x12b\n" +
	"\rRemoveNetwork\x12'.arca.wireguard.v1.RemoveNetworkRequest\x1a(.arca.wireguard.v1.RemoveNetworkResponse\x12k\n" +
	"\x10UpdateAllowedIPs\x12*.arca.wireguard.v1.UpdateAllowedIPsRequest\x1a+.arca.wireguard.v1.UpdateAllowedIPsResponse\x12V\n" +
	"\tDeleteHub\x12#.arca.wireguard.v1.DeleteHubRequest\x1a$.arca.wireguard.v1.DeleteHubResponse\x12V\n" +
	"\tGetStatus\x12#.arca.wireguard.v1.GetStatusRequest\x1a$.arca.wireguard.v1.GetStatusResponseB5Z3github.com/vas-solutus/arca-wireguard-service/protob\x06proto3"

var (
	file_proto_wireguard_proto_rawDescOnce sync.Once
	file_proto_wireguard_proto_rawDescData []byte
)

func file_proto_wireguard_proto_rawDescGZIP() []byte {
	file_proto_wireguard_proto_rawDescOnce.Do(func() {
		file_proto_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wireguard_proto_rawDesc), len(file_proto_wireguard_proto_rawDesc)))
	})
	return file_proto_wireguard_proto_rawDescData
}

var file_proto_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_wireguard_proto_goTypes = []any{
	(*CreateHubRequest)(nil),         // 0: arca.wireguard.v1.CreateHubRequest
	(*CreateHubResponse)(nil),        // 1: arca.wireguard.v1.CreateHubResponse
	(*AddNetworkRequest)(nil),        // 2: arca.wireguard.v1.AddNetworkRequest
	(*AddNetworkResponse)(nil),       // 3: arca.wireguard.v1.AddNetworkResponse
	(*RemoveNetworkRequest)(nil),     // 4: arca.wireguard.v1.RemoveNetworkRequest
	(*RemoveNetworkResponse)(nil),    // 5: arca.wireguard.v1.RemoveNetworkResponse
	(*UpdateAllowedIPsRequest)(nil),  // 6: arca.wireguard.v1.UpdateAllowedIPsRequest
	(*UpdateAllowedIPsResponse)(nil), // 7: arca.wireguard.v1.UpdateAllowedIPsResponse
	(*DeleteHubRequest)(nil),         // 8: arca.wireguard.v1.DeleteHubRequest
	(*DeleteHubResponse)(nil),        // 9: arca.wireguard.v1.DeleteHubResponse
	(*GetStatusRequest)(nil),         // 10: arca.wireguard.v1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 11: arca.wireguard.v1.GetStatusResponse
	(*InterfaceStatus)(nil),          // 12: arca.wireguard.v1.InterfaceStatus
	(*PeerStatus)(nil),               // 13: arca.wireguard.v1.PeerStatus
	(*TransferStats)(nil),            // 14: arca.wireguard.v1.TransferStats
}
var file_proto_wireguard_proto_depIdxs = []int32{
	12, // 0: arca.wireguard.v1.GetStatusResponse.interface:type_name -> arca.wireguard.v1.InterfaceStatus
	13, // 1: arca.wireguard.v1.GetStatusResponse.peers:type_name -> arca.wireguard.v1.PeerStatus
	14, // 2: arca.wireguard.v1.PeerStatus.stats:type_name -> arca.wireguard.v1.TransferStats
	0,  // 3: arca.wireguard.v1.WireGuardService.CreateHub:input_type -> arca.wireguard.v1.CreateHubRequest
	2,  // 4: arca.wireguard.v1.WireGuardService.AddNetwork:input_type -> arca.wireguard.v1.AddNetworkRequest
	4,  // 5: arca.wireguard.v1.WireGuardService.RemoveNetwork:input_type -> arca.wireguard.v1.RemoveNetworkRequest
	6,  // 6: arca.wireguard.v1.WireGuardService.UpdateAllowedIPs:input_type -> arca.wireguard.v1.UpdateAllowedIPsRequest
	8,  // 7: arca.wireguard.v1.WireGuardService.DeleteHub:input_type -> arca.wireguard.v1.DeleteHubRequest
	10, // 8: arca.wireguard.v1.WireGuardService.GetStatus:input_type -> arca.wireguard.v1.GetStatusRequest
	1,  // 9: arca.wireguard.v1.WireGuardService.CreateHub:output_type -> arca.wireguard.v1.CreateHubResponse
	3,  // 10: arca.wireguard.v1.WireGuardService.AddNetwork:output_type -> arca.wireguard.v1.AddNetworkResponse
	5,  // 11: arca.wireguard.v1.WireGuardService.RemoveNetwork:output_type -> arca.wireguard.v1.RemoveNetworkResponse
	7,  // 12: arca.wireguard.v1.WireGuardService.UpdateAllowedIPs:output_type -> arca.wireguard.v1.UpdateAllowedIPsResponse
	9,  // 13: arca.wireguard.v1.WireGuardService.DeleteHub:output_type -> arca.wireguard.v1.DeleteHubResponse
	11, // 14: arca.wireguard.v1.WireGuardService.GetStatus:output_type -> arca.wireguard.v1.GetStatusResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_wireguard_proto_init() }
func file_proto_wireguard_proto_init() {
	if File_proto_wireguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wireguard_proto_rawDesc), len(file_proto_wireguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wireguard_proto_goTypes,
		DependencyIndexes: file_proto_wireguard_proto_depIdxs,
		MessageInfos:      file_proto_wireguard_proto_msgTypes,
	}.Build()
	File_proto_wireguard_proto = out.File
	file_proto_wireguard_proto_goTypes = nil
	file_proto_wireguard_proto_depIdxs = nil
}
