// Arca WireGuard Network Service Protocol
// gRPC API for WireGuard-based container networking

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/wireguard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireGuardService_CreateHub_FullMethodName        = "/arca.wireguard.v1.WireGuardService/CreateHub"
	WireGuardService_AddNetwork_FullMethodName       = "/arca.wireguard.v1.WireGuardService/AddNetwork"
	WireGuardService_RemoveNetwork_FullMethodName    = "/arca.wireguard.v1.WireGuardService/RemoveNetwork"
	WireGuardService_UpdateAllowedIPs_FullMethodName = "/arca.wireguard.v1.WireGuardService/UpdateAllowedIPs"
	WireGuardService_DeleteHub_FullMethodName        = "/arca.wireguard.v1.WireGuardService/DeleteHub"
	WireGuardService_GetStatus_FullMethodName        = "/arca.wireguard.v1.WireGuardService/GetStatus"
)

// WireGuardServiceClient is the client API for WireGuardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WireGuardService manages WireGuard hubs and peer connections for container networking
// Runs on vsock port 51820 in container's init system namespace
type WireGuardServiceClient interface {
	// Create a new WireGuard hub (called once per container, creates wg0 interface)
	CreateHub(ctx context.Context, in *CreateHubRequest, opts ...grpc.CallOption) (*CreateHubResponse, error)
	// Add a network to this container's WireGuard hub (configures allowed-ips routing)
	AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error)
	// Remove a network from this container's WireGuard hub
	RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error)
	// Update allowed IPs for multi-network routing (called when topology changes)
	UpdateAllowedIPs(ctx context.Context, in *UpdateAllowedIPsRequest, opts ...grpc.CallOption) (*UpdateAllowedIPsResponse, error)
	// Delete the WireGuard hub (called during container removal)
	DeleteHub(ctx context.Context, in *DeleteHubRequest, opts ...grpc.CallOption) (*DeleteHubResponse, error)
	// Get WireGuard status and statistics
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type wireGuardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireGuardServiceClient(cc grpc.ClientConnInterface) WireGuardServiceClient {
	return &wireGuardServiceClient{cc}
}

func (c *wireGuardServiceClient) CreateHub(ctx context.Context, in *CreateHubRequest, opts ...grpc.CallOption) (*CreateHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHubResponse)
	err := c.cc.Invoke(ctx, WireGuardService_CreateHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkResponse)
	err := c.cc.Invoke(ctx, WireGuardService_AddNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNetworkResponse)
	err := c.cc.Invoke(ctx, WireGuardService_RemoveNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) UpdateAllowedIPs(ctx context.Context, in *UpdateAllowedIPsRequest, opts ...grpc.CallOption) (*UpdateAllowedIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAllowedIPsResponse)
	err := c.cc.Invoke(ctx, WireGuardService_UpdateAllowedIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) DeleteHub(ctx context.Context, in *DeleteHubRequest, opts ...grpc.CallOption) (*DeleteHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHubResponse)
	err := c.cc.Invoke(ctx, WireGuardService_DeleteHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, WireGuardService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireGuardServiceServer is the server API for WireGuardService service.
// All implementations must embed UnimplementedWireGuardServiceServer
// for forward compatibility.
//
// WireGuardService manages WireGuard hubs and peer connections for container networking
// Runs on vsock port 51820 in container's init system namespace
type WireGuardServiceServer interface {
	// Create a new WireGuard hub (called once per container, creates wg0 interface)
	CreateHub(context.Context, *CreateHubRequest) (*CreateHubResponse, error)
	// Add a network to this container's WireGuard hub (configures allowed-ips routing)
	AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error)
	// Remove a network from this container's WireGuard hub
	RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error)
	// Update allowed IPs for multi-network routing (called when topology changes)
	UpdateAllowedIPs(context.Context, *UpdateAllowedIPsRequest) (*UpdateAllowedIPsResponse, error)
	// Delete the WireGuard hub (called during container removal)
	DeleteHub(context.Context, *DeleteHubRequest) (*DeleteHubResponse, error)
	// Get WireGuard status and statistics
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedWireGuardServiceServer()
}

// UnimplementedWireGuardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireGuardServiceServer struct{}

func (UnimplementedWireGuardServiceServer) CreateHub(context.Context, *CreateHubRequest) (*CreateHubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHub not implemented")
}
func (UnimplementedWireGuardServiceServer) AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNetwork not implemented")
}
func (UnimplementedWireGuardServiceServer) RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNetwork not implemented")
}
func (UnimplementedWireGuardServiceServer) UpdateAllowedIPs(context.Context, *UpdateAllowedIPsRequest) (*UpdateAllowedIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAllowedIPs not implemented")
}
func (UnimplementedWireGuardServiceServer) DeleteHub(context.Context, *DeleteHubRequest) (*DeleteHubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHub not implemented")
}
func (UnimplementedWireGuardServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedWireGuardServiceServer) mustEmbedUnimplementedWireGuardServiceServer() {}
func (UnimplementedWireGuardServiceServer) testEmbeddedByValue()                          {}

// UnsafeWireGuardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireGuardServiceServer will
// result in compilation errors.
type UnsafeWireGuardServiceServer interface {
	mustEmbedUnimplementedWireGuardServiceServer()
}

func RegisterWireGuardServiceServer(s grpc.ServiceRegistrar, srv WireGuardServiceServer) {
	// If the following call pancis, it indicates UnimplementedWireGuardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireGuardService_ServiceDesc, srv)
}

func _WireGuardService_CreateHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).CreateHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_CreateHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).CreateHub(ctx, req.(*CreateHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_AddNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).AddNetwork(ctx, req.(*AddNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_RemoveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).RemoveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_RemoveNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).RemoveNetwork(ctx, req.(*RemoveNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_UpdateAllowedIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAllowedIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).UpdateAllowedIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_UpdateAllowedIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).UpdateAllowedIPs(ctx, req.(*UpdateAllowedIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_DeleteHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).DeleteHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_DeleteHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).DeleteHub(ctx, req.(*DeleteHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireGuardService_ServiceDesc is the grpc.ServiceDesc for WireGuardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireGuardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.wireguard.v1.WireGuardService",
	HandlerType: (*WireGuardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHub",
			Handler:    _WireGuardService_CreateHub_Handler,
		},
		{
			MethodName: "AddNetwork",
			Handler:    _WireGuardService_AddNetwork_Handler,
		},
		{
			MethodName: "RemoveNetwork",
			Handler:    _WireGuardService_RemoveNetwork_Handler,
		},
		{
			MethodName: "UpdateAllowedIPs",
			Handler:    _WireGuardService_UpdateAllowedIPs_Handler,
		},
		{
			MethodName: "DeleteHub",
			Handler:    _WireGuardService_DeleteHub_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _WireGuardService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wireguard.proto",
}
