// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: overlayfs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OverlayFSService_MountOverlay_FullMethodName   = "/arca.overlayfs.v1.OverlayFSService/MountOverlay"
	OverlayFSService_UnmountOverlay_FullMethodName = "/arca.overlayfs.v1.OverlayFSService/UnmountOverlay"
)

// OverlayFSServiceClient is the client API for OverlayFSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # OverlayFS mounting service for stacked layer filesystems
//
// This service runs inside each container's Linux VM and provides
// OverlayFS mounting capabilities for the Arca container runtime.
//
// Architecture:
// - Lower layers: Read-only EXT4 filesystems (image layers)
// - Upper layer: Read-write directory for container changes
// - Work directory: OverlayFS metadata directory
// - Target: Mount point (typically /)
type OverlayFSServiceClient interface {
	// Mount OverlayFS with multiple lower layers
	//
	// Stacks multiple read-only layers with a read-write upper layer.
	// Lower layers are ordered from top to bottom (reverse of input).
	//
	// Example:
	//
	//	lower_block_devices: ["/dev/vda", "/dev/vdb", "/dev/vdc"]
	//	-> OverlayFS: vdc:vdb:vda (bottom to top)
	MountOverlay(ctx context.Context, in *MountOverlayRequest, opts ...grpc.CallOption) (*MountOverlayResponse, error)
	// Unmount OverlayFS
	//
	// Unmounts the overlay filesystem and cleans up lower layer mounts.
	UnmountOverlay(ctx context.Context, in *UnmountOverlayRequest, opts ...grpc.CallOption) (*UnmountOverlayResponse, error)
}

type overlayFSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOverlayFSServiceClient(cc grpc.ClientConnInterface) OverlayFSServiceClient {
	return &overlayFSServiceClient{cc}
}

func (c *overlayFSServiceClient) MountOverlay(ctx context.Context, in *MountOverlayRequest, opts ...grpc.CallOption) (*MountOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountOverlayResponse)
	err := c.cc.Invoke(ctx, OverlayFSService_MountOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayFSServiceClient) UnmountOverlay(ctx context.Context, in *UnmountOverlayRequest, opts ...grpc.CallOption) (*UnmountOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmountOverlayResponse)
	err := c.cc.Invoke(ctx, OverlayFSService_UnmountOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverlayFSServiceServer is the server API for OverlayFSService service.
// All implementations must embed UnimplementedOverlayFSServiceServer
// for forward compatibility.
//
// # OverlayFS mounting service for stacked layer filesystems
//
// This service runs inside each container's Linux VM and provides
// OverlayFS mounting capabilities for the Arca container runtime.
//
// Architecture:
// - Lower layers: Read-only EXT4 filesystems (image layers)
// - Upper layer: Read-write directory for container changes
// - Work directory: OverlayFS metadata directory
// - Target: Mount point (typically /)
type OverlayFSServiceServer interface {
	// Mount OverlayFS with multiple lower layers
	//
	// Stacks multiple read-only layers with a read-write upper layer.
	// Lower layers are ordered from top to bottom (reverse of input).
	//
	// Example:
	//
	//	lower_block_devices: ["/dev/vda", "/dev/vdb", "/dev/vdc"]
	//	-> OverlayFS: vdc:vdb:vda (bottom to top)
	MountOverlay(context.Context, *MountOverlayRequest) (*MountOverlayResponse, error)
	// Unmount OverlayFS
	//
	// Unmounts the overlay filesystem and cleans up lower layer mounts.
	UnmountOverlay(context.Context, *UnmountOverlayRequest) (*UnmountOverlayResponse, error)
	mustEmbedUnimplementedOverlayFSServiceServer()
}

// UnimplementedOverlayFSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverlayFSServiceServer struct{}

func (UnimplementedOverlayFSServiceServer) MountOverlay(context.Context, *MountOverlayRequest) (*MountOverlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountOverlay not implemented")
}
func (UnimplementedOverlayFSServiceServer) UnmountOverlay(context.Context, *UnmountOverlayRequest) (*UnmountOverlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmountOverlay not implemented")
}
func (UnimplementedOverlayFSServiceServer) mustEmbedUnimplementedOverlayFSServiceServer() {}
func (UnimplementedOverlayFSServiceServer) testEmbeddedByValue()                          {}

// UnsafeOverlayFSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverlayFSServiceServer will
// result in compilation errors.
type UnsafeOverlayFSServiceServer interface {
	mustEmbedUnimplementedOverlayFSServiceServer()
}

func RegisterOverlayFSServiceServer(s grpc.ServiceRegistrar, srv OverlayFSServiceServer) {
	// If the following call pancis, it indicates UnimplementedOverlayFSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OverlayFSService_ServiceDesc, srv)
}

func _OverlayFSService_MountOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayFSServiceServer).MountOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayFSService_MountOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayFSServiceServer).MountOverlay(ctx, req.(*MountOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OverlayFSService_UnmountOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayFSServiceServer).UnmountOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OverlayFSService_UnmountOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayFSServiceServer).UnmountOverlay(ctx, req.(*UnmountOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OverlayFSService_ServiceDesc is the grpc.ServiceDesc for OverlayFSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OverlayFSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.overlayfs.v1.OverlayFSService",
	HandlerType: (*OverlayFSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountOverlay",
			Handler:    _OverlayFSService_MountOverlay_Handler,
		},
		{
			MethodName: "UnmountOverlay",
			Handler:    _OverlayFSService_UnmountOverlay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "overlayfs.proto",
}
