// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: overlayfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountOverlayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block device paths in guest (e.g., /dev/vda, /dev/vdb, ...)
	// Ordered from bottom layer to top layer
	LowerBlockDevices []string `protobuf:"bytes,1,rep,name=lower_block_devices,json=lowerBlockDevices,proto3" json:"lower_block_devices,omitempty"`
	// Upper directory for writable layer (VirtioFS mount point)
	UpperDir string `protobuf:"bytes,2,opt,name=upper_dir,json=upperDir,proto3" json:"upper_dir,omitempty"`
	// Work directory for OverlayFS metadata (VirtioFS mount point)
	WorkDir string `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	// Target mount point (usually /)
	Target        string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountOverlayRequest) Reset() {
	*x = MountOverlayRequest{}
	mi := &file_overlayfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountOverlayRequest) ProtoMessage() {}

func (x *MountOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlayfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountOverlayRequest.ProtoReflect.Descriptor instead.
func (*MountOverlayRequest) Descriptor() ([]byte, []int) {
	return file_overlayfs_proto_rawDescGZIP(), []int{0}
}

func (x *MountOverlayRequest) GetLowerBlockDevices() []string {
	if x != nil {
		return x.LowerBlockDevices
	}
	return nil
}

func (x *MountOverlayRequest) GetUpperDir() string {
	if x != nil {
		return x.UpperDir
	}
	return ""
}

func (x *MountOverlayRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *MountOverlayRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type MountOverlayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountOverlayResponse) Reset() {
	*x = MountOverlayResponse{}
	mi := &file_overlayfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountOverlayResponse) ProtoMessage() {}

func (x *MountOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlayfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountOverlayResponse.ProtoReflect.Descriptor instead.
func (*MountOverlayResponse) Descriptor() ([]byte, []int) {
	return file_overlayfs_proto_rawDescGZIP(), []int{1}
}

func (x *MountOverlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MountOverlayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UnmountOverlayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target mount point to unmount
	Target        string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountOverlayRequest) Reset() {
	*x = UnmountOverlayRequest{}
	mi := &file_overlayfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountOverlayRequest) ProtoMessage() {}

func (x *UnmountOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlayfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountOverlayRequest.ProtoReflect.Descriptor instead.
func (*UnmountOverlayRequest) Descriptor() ([]byte, []int) {
	return file_overlayfs_proto_rawDescGZIP(), []int{2}
}

func (x *UnmountOverlayRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type UnmountOverlayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountOverlayResponse) Reset() {
	*x = UnmountOverlayResponse{}
	mi := &file_overlayfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountOverlayResponse) ProtoMessage() {}

func (x *UnmountOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlayfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountOverlayResponse.ProtoReflect.Descriptor instead.
func (*UnmountOverlayResponse) Descriptor() ([]byte, []int) {
	return file_overlayfs_proto_rawDescGZIP(), []int{3}
}

func (x *UnmountOverlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnmountOverlayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_overlayfs_proto protoreflect.FileDescriptor

const file_overlayfs_proto_rawDesc = "" +
	"\n" +
	"\x0foverlayfs.proto\x12\x11arca.overlayfs.v1\"\x95\x01\n" +
	"\x13MountOverlayRequest\x12.\n" +
	"\x13lower_block_devices\x18\x01 \x03(\tR\x11lowerBlockDevices\x12\x1b\n" +
	"\tupper_dir\x18\x02 \x01(\tR\bupperDir\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"U\n" +
	"\x14MountOverlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"/\n" +
	"\x15UnmountOverlayRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"W\n" +
	"\x16UnmountOverlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xda\x01\n" +
	"\x10OverlayFSService\x12_\n" +
	"\fMountOverlay\x12&.arca.overlayfs.v1.MountOverlayRequest\x1a'.arca.overlayfs.v1.MountOverlayResponse\x12e\n" +
	"\x0eUnmountOverlay\x12(.arca.overlayfs.v1.UnmountOverlayRequest\x1a).arca.overlayfs.v1.UnmountOverlayResponseBNZLgithub.com/apple/containerization/vminitd/extensions/overlayfs-mounter/protob\x06proto3"

var (
	file_overlayfs_proto_rawDescOnce sync.Once
	file_overlayfs_proto_rawDescData []byte
)

func file_overlayfs_proto_rawDescGZIP() []byte {
	file_overlayfs_proto_rawDescOnce.Do(func() {
		file_overlayfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overlayfs_proto_rawDesc), len(file_overlayfs_proto_rawDesc)))
	})
	return file_overlayfs_proto_rawDescData
}

var file_overlayfs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_overlayfs_proto_goTypes = []any{
	(*MountOverlayRequest)(nil),    // 0: arca.overlayfs.v1.MountOverlayRequest
	(*MountOverlayResponse)(nil),   // 1: arca.overlayfs.v1.MountOverlayResponse
	(*UnmountOverlayRequest)(nil),  // 2: arca.overlayfs.v1.UnmountOverlayRequest
	(*UnmountOverlayResponse)(nil), // 3: arca.overlayfs.v1.UnmountOverlayResponse
}
var file_overlayfs_proto_depIdxs = []int32{
	0, // 0: arca.overlayfs.v1.OverlayFSService.MountOverlay:input_type -> arca.overlayfs.v1.MountOverlayRequest
	2, // 1: arca.overlayfs.v1.OverlayFSService.UnmountOverlay:input_type -> arca.overlayfs.v1.UnmountOverlayRequest
	1, // 2: arca.overlayfs.v1.OverlayFSService.MountOverlay:output_type -> arca.overlayfs.v1.MountOverlayResponse
	3, // 3: arca.overlayfs.v1.OverlayFSService.UnmountOverlay:output_type -> arca.overlayfs.v1.UnmountOverlayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_overlayfs_proto_init() }
func file_overlayfs_proto_init() {
	if File_overlayfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overlayfs_proto_rawDesc), len(file_overlayfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_overlayfs_proto_goTypes,
		DependencyIndexes: file_overlayfs_proto_depIdxs,
		MessageInfos:      file_overlayfs_proto_msgTypes,
	}.Build()
	File_overlayfs_proto = out.File
	file_overlayfs_proto_goTypes = nil
	file_overlayfs_proto_depIdxs = nil
}
